//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : MetaMask Unity SDK ABI Code Generator
//   Input filename:  ERC20PresetFixedSupply.sol
//   Output filename: ERC20PresetFixedSupplyBacking.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------

#if UNITY_EDITOR || !ENABLE_MONO
using System;
using System.Numerics;
using System.Threading.Tasks;
using evm.net;
using evm.net.Models;

namespace MetaMask.Contracts
{
	public class ERC20PresetFixedSupplyBacking : Contract, ERC20PresetFixedSupply
	{
		public string Address
		{
			get => base.Address;
		}
		public ERC20PresetFixedSupplyBacking(IProvider provider, EvmAddress address, Type interfaceType) : base(provider, address, interfaceType)
		{
		}
		public Task<ERC20PresetFixedSupply> DeployNew(String name, String symbol, BigInteger initialSupply, EvmAddress owner)
		{
			var method = System.Reflection.MethodBase.GetCurrentMethod();
			return (Task<ERC20PresetFixedSupply>) InvokeMethod(method, new object[] { name, symbol, initialSupply, owner });
		}
		
		[EvmMethodInfo(Name = "allowance", View = true)]
		public Task<BigInteger> Allowance(EvmAddress owner, EvmAddress spender)
		{
			var method = System.Reflection.MethodBase.GetCurrentMethod();
			return (Task<BigInteger>) InvokeMethod(method, new object[] { owner, spender });
		}
		
		[EvmMethodInfo(Name = "approve", View = false)]
		public Task<Transaction> Approve(EvmAddress spender, BigInteger amount)
		{
			var method = System.Reflection.MethodBase.GetCurrentMethod();
			return (Task<Transaction>) InvokeMethod(method, new object[] { spender, amount });
		}
		
		[EvmMethodInfo(Name = "balanceOf", View = true)]
		public Task<BigInteger> BalanceOf(EvmAddress account)
		{
			var method = System.Reflection.MethodBase.GetCurrentMethod();
			return (Task<BigInteger>) InvokeMethod(method, new object[] { account });
		}
		
		[EvmMethodInfo(Name = "burn", View = false)]
		public Task<Transaction> Burn(BigInteger amount)
		{
			var method = System.Reflection.MethodBase.GetCurrentMethod();
			return (Task<Transaction>) InvokeMethod(method, new object[] { amount });
		}
		
		[EvmMethodInfo(Name = "burnFrom", View = false)]
		public Task<Transaction> BurnFrom(EvmAddress account, BigInteger amount)
		{
			var method = System.Reflection.MethodBase.GetCurrentMethod();
			return (Task<Transaction>) InvokeMethod(method, new object[] { account, amount });
		}
		
		[EvmMethodInfo(Name = "decimals", View = true)]
		[return: EvmParameterInfo(Type = "uint8")]
		public Task<UInt16> Decimals()
		{
			var method = System.Reflection.MethodBase.GetCurrentMethod();
			return (Task<UInt16>) InvokeMethod(method, new object[] {  });
		}
		
		[EvmMethodInfo(Name = "decreaseAllowance", View = false)]
		public Task<Transaction> DecreaseAllowance(EvmAddress spender, BigInteger subtractedValue)
		{
			var method = System.Reflection.MethodBase.GetCurrentMethod();
			return (Task<Transaction>) InvokeMethod(method, new object[] { spender, subtractedValue });
		}
		
		[EvmMethodInfo(Name = "increaseAllowance", View = false)]
		public Task<Transaction> IncreaseAllowance(EvmAddress spender, BigInteger addedValue)
		{
			var method = System.Reflection.MethodBase.GetCurrentMethod();
			return (Task<Transaction>) InvokeMethod(method, new object[] { spender, addedValue });
		}
		
		[EvmMethodInfo(Name = "name", View = true)]
		public Task<String> Name()
		{
			var method = System.Reflection.MethodBase.GetCurrentMethod();
			return (Task<String>) InvokeMethod(method, new object[] {  });
		}
		
		[EvmMethodInfo(Name = "symbol", View = true)]
		public Task<String> Symbol()
		{
			var method = System.Reflection.MethodBase.GetCurrentMethod();
			return (Task<String>) InvokeMethod(method, new object[] {  });
		}
		
		[EvmMethodInfo(Name = "totalSupply", View = true)]
		public Task<BigInteger> TotalSupply()
		{
			var method = System.Reflection.MethodBase.GetCurrentMethod();
			return (Task<BigInteger>) InvokeMethod(method, new object[] {  });
		}
		
		[EvmMethodInfo(Name = "transfer", View = false)]
		public Task<Transaction> Transfer(EvmAddress to, BigInteger amount)
		{
			var method = System.Reflection.MethodBase.GetCurrentMethod();
			return (Task<Transaction>) InvokeMethod(method, new object[] { to, amount });
		}
		
		[EvmMethodInfo(Name = "transferFrom", View = false)]
		public Task<Transaction> TransferFrom(EvmAddress from, EvmAddress to, BigInteger amount)
		{
			var method = System.Reflection.MethodBase.GetCurrentMethod();
			return (Task<Transaction>) InvokeMethod(method, new object[] { from, to, amount });
		}
		
	}
}
#endif
