name: Duplicate Samples 🪞

on:
  workflow_call:
    
jobs:
  setup:
    name: Duplicate job
    uses: ChainSafe/web3.unity/.github/workflows/setup.yaml@main
    with:
      arguments: "-duplicate_samples"
    secrets: inherit