name: Duplicate Package Samples Workflow

on:
  push:
    branches: [ rob/samples-import-fixes-642 ]

jobs:
  duplicate:
    name: Duplicate samples job 👯
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run duplicate script file
      run: |
        chmod +x scripts/duplicate-sample.sh
        scripts/duplicate-sample.sh $web3_unity_imported_sample_path $web3_unity_importable_sample_path
        scripts/duplicate-sample.sh $web3_auth_imported_sample_path $web3_auth_importable_sample_path
      env:
        web3_unity_imported_sample_path: "src/UnitySampleProject/Assets/Samples/web3.unity SDK/$(ls 'src/UnitySampleProject/Assets/Samples/web3.unity SDK' | head -n 1)Web3.Unity Samples/"
        web3_unity_importable_sample_path: "Packages/io.chainsafe.web3-unity/Samples~/Web3.Unity/"
        web3_auth_imported_sample_path: "src/UnitySampleProject/Assets/Samples/web3.unity SDK Web3Auth/$(ls 'src/UnitySampleProject/Assets/Samples/web3.unity SDK Web3Auth' | head -n 1)Web3.Unity Web3Auth Samples/"
        web3_auth_importable_sample_path: "Packages/io.chainsafe.web3-unity.web3auth/Samples~/Web3.Unity Web3Auth/"
    
    - name: Commit and Push
      run: |
        git config user.email $git_email
        git config user.name "${{ github.actor }}"
        git add ./Packages/io.chainsafe.web3-unity/Samples~/Web3.Unity/. -f
        git add ./Packages/io.chainsafe.web3-unity.web3auth/Samples~/Web3.Unity Web3Auth/. -f
        git diff-index --cached --quiet HEAD || git commit -m "Auto-duplicate Packages Samples"
        git push
      env:
        git_email: "${{ github.actor }}@users.noreply.github.com"