name: Duplicate Package Sample Workflow

on:
  pull_request:
    branches: [main]

jobs:
  duplicate:
    name: Duplicate samples job 👯
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run duplicate script file
        run: |
          export SOURCE_DIRECTORY="${GITHUB_WORKSPACE}/src/UnitySampleProject/Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/"
          export DESTINATION_DIRECTORY="${GITHUB_WORKSPACE}/Packages/io.chainsafe.web3-unity/Samples~/Web3.Unity/"
          rm -r "$DESTINATION_DIRECTORY"
          cp -r "$SOURCE_DIRECTORY" "$DESTINATION_DIRECTORY"

      - name: Commit and Push
        run: |
          git config user.email $git_email
          git config user.name "${{ github.actor }}"
          git add ./Packages/io.chainsafe.web3-unity/Samples~/Web3.Unity/. -f
          git diff-index --cached --quiet HEAD || git commit -m "Auto-duplicate Package Samples"
          git push
        env:
          git_email: "${{ github.actor }}@users.noreply.github.com"