name: Duplicate Package Sample

on:
  pull_request:
    branches:
      - main

jobs:
  duplicate:
    name: duplicate package sample
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run duplicate script file
        run: bash ${GITHUB_WORKSPACE}/duplicate_package_sample.sh

      - name: Commit and Push
        run: |
          git config user.email $git_email
          git config user.name "${{ github.actor }}"
          git add ./Packages/io.chainsafe.web3-unity/Samples~/Web3.Unity/. -f
          git diff-index --cached --quiet HEAD || git commit -m "Auto-duplicate Package Samples"
          git push
        env:
          git_email: "${{ github.actor }}@users.noreply.github.com"