name: Create Unity Package on release tag

on: 
  push:
    tags:
      - v2.*

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        find Assets/Editor/ -name \*.meta > metaList
        find Assets/Plugins/ -name \*.meta >> metaList
        find Assets/Resources/ -name \*.meta >> metaList
        find Assets/Web3Unity/ -name \*.meta >> metaList
        find Assets/WebGLTemplates/ -name \*.meta >> metaList
        echo metaList

    - run: mkdir output

    - name: Set release version ENV
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'output/web3.unitypackage'
        include-files: metaList
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        generate_release_notes: true
        files: output/web3.unitypackage