name: Create Unity Package on push

on: 
  push:
    branches: 
      - package-fix

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        find Editor/ -name \*.meta > metaList
        find Plugins/ -name \*.meta >> metaList
        find Resources/ -name \*.meta >> metaList
        find Web3Unity/ -name \*.meta >> metaList
        find WebGLTemplates/ -name \*.meta >> metaList
        echo metaList

    - run: mkdir output

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'output/web3.unitypackage'
        include-files: metaList
        project-folder: "./Assets/"
    - uses: actions/upload-artifact@master
      with:
        path: output
        name: package