name: Merge Checks

on:
  pull_request:
    branches:
      - main
      - dev
    types:
      - labeled
      - ready_for_review

jobs:
  web3_tests:
    name: Web3 Tests
    if: ${{ github.event.action == 'ready_for_review' || github.event.label.name == 'ready-to-merge'}}
    uses: ChainSafe/web3.unity/.github/workflows/test.yaml@main
  analyze_code:
    name: Analyze Code
    uses: ChainSafe/web3.unity/.github/workflows/codeql.yml@main
    needs: [ web3_tests ]
  unity_tests:
    name: Unity Tests
    if: ${{ github.event.pull_request.head.ref == 'main' }}
    uses: ChainSafe/web3.unity/.github/workflows/check_and_commit.yml@main
    needs: [ analyze_code ]
    secrets: inherit