name: Merge Checks

on:
  pull_request:
    branches: [ main ]
    types:
      - labeled
      - ready_for_review

jobs:
  web3_tests:
    name: Web3 Tests
    if: ${{ github.event.action == 'ready_for_review' || github.event.label.name == 'ready-to-merge'}}
    uses: ChainSafe/web3.unity/.github/workflows/test.yaml@main
  unity_tests:
    name: Unity Tests
    uses: ChainSafe/web3.unity/.github/workflows/unity_tests.yml@main
    needs: [web3_tests]
    secrets: inherit
  analyze_code:
    name: Analyze Code
    uses: ChainSafe/web3.unity/.github/workflows/codeql.yml@main
    needs: [unity_tests]