name: Auto Commits

on:
  pull_request:
    branches: [ main ]

jobs:
  duplicate_samples:
    name: Duplicate Samples
    uses: ChainSafe/web3.unity/.github/workflows/duplicate_samples.yml@main
  publish_dependencies:
    name: Publish Dependencies
    uses: ChainSafe/web3.unity/.github/workflows/publish_dependencies.yml@rob/ci-improvement-785
    needs: [duplicate_samples]