name: Post Push Checks

on:
  push:
    branches: [ rob/sync-branches-ci-fix ]

jobs:
  sync_branches:
    name: Sync Branches ♾️
    uses: ChainSafe/web3.unity/.github/workflows/sync_branches.yaml@rob/sync-branches-ci-fix
    with:
      base: main
      target: dev
    secrets: inherit