name: Re-author
on:
  workflow_dispatch:
    inputs:
      previous_email:
        required: true
        description: 'Author to change (email)'
        type: string
      new_email:
        required: true
        description: 'New author email'
        type: string
      new_username:
        required: true
        description: 'New author username'
        type: string

jobs:
  reauthor:
    name: Re-author job
    runs-on: ubuntu-latest
    steps:
      - name: Set-up SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Clone and Re-author
        run: |
          git clone --bare git@github.com:ChainSafe/web3.unity.git
          
          cd web3.unity.git
          
          git config user.email "$new_email"
          
          git config user.name $new_username
          
          #!/bin/sh

          git filter-branch -f --env-filter '
          OLD_EMAIL="$previous_email"
          CORRECT_NAME="$new_username"
          CORRECT_EMAIL="$new_email"
          if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
          then
              export GIT_COMMITTER_NAME="$CORRECT_NAME"
              export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
          fi
          if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
          then
              export GIT_AUTHOR_NAME="$CORRECT_NAME"
              export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
          fi
          ' --tag-name-filter cat -- --branches --tags
          git push --force --tags origin 'refs/heads/*'
        env:
          previous_email: ${{ github.event.inputs.previous_email }}
          new_email: ${{ github.event.inputs.new_email }}
          new_username: ${{ github.event.inputs.new_username }}