name: Release ⬆️

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to Release'
        required: true
      release_notes:
        description: 'Version Release Notes'
        required: true

jobs:
  setup:
    name: Setup job
    uses: ChainSafe/web3.unity/.github/workflows/setup.yaml@main
    with:
      arguments: "--deploy ${{ github.event.inputs.version }}"
    secrets: inherit
  release:
    name: Release job
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: |
            ${{ github.event.inputs.release_notes }}
          draft: false
          prerelease: false