name: Setup Workflow

on:
  workflow_call:
    inputs:
      arguments:
        required: true
        type: string

env:
  git_email: "${{ github.actor }}@users.noreply.github.com"
  git_actor: "${{ github.actor }}"

jobs:
  setup:
    name: Setup job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Run
        run: |
          cd Setup
          dotnet run${{ inputs.arguments }} Setup/Setup.csproj