name: Setup ⚙️

on:
  workflow_call:
    inputs:
      arguments:
        required: true
        type: string
      configuration:
        required: false
        type: string
        default: "Release"
  workflow_dispatch: 
    inputs:
      arguments:
        required: true
        description: 'Arguments to pass to the setup script'
        type: string
      configuration:
        required: true
        description: 'Run Configuration'
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug
env:
  git_email: "${{ github.actor }}@users.noreply.github.com"
  git_actor: "${{ github.actor }}"

jobs:
  setup:
    name: Setup job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          lfs: true
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          submodules: recursive
          fetch-depth: 100
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Run
        run: |
          cd Setup
          dotnet run ${{ inputs.arguments || github.event.inputs.arguments }} -c ${{ inputs.configuration || github.event.inputs.configuration }}
          git reset --hard