name: Sync Branches

on:
  workflow_call:
    inputs:
      base:
        required: true
        type: string
      target:
        required: true
        type: string
      skip_ci:
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      base:
        required: true
        description: "Base branch to Sync"
        type: string
      target:
        required: true
        description: "Target branch to Sync"
        type: string
      skip_ci:
        required: true
        description: "Should push also skip CI"
        type: boolean
        default: true

env:
  message: "Auto Sync with ${{ inputs.base }}"
  base: ${{ github.event.inputs.base || inputs.base }}
  target: ${{ github.event.inputs.target || inputs.target }}

jobs:
  sync:
    name: Sync Branches ♾️
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set Automation
        if: ${{ inputs.skip_ci }}
        run: |
          skip_ci=" [skip-ci]"
          echo "message=$message$skip_ci" >> $GITHUB_ENV
      - name: Sync Branches
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ env.base }}
          target_branch: ${{ env.target }}
          message: ${{ env.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}