name: Sync Branches

on:
  workflow_call:
    inputs:
      base:
        required: true
        type: string
      target:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      base:
        required: true
        description: "Base branch to Sync"
        type: string
      target:
        required: true
        description: "Target branch to Sync"
        type: string

jobs:
  setup:
    name: Sync Branches ♾️
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Sync Branches
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ inputs.base }}
          target_branch: ${{ inputs.target }}
          github_token: ${{ secrets.GITHUB_TOKEN }}