name: Sync Branches

on:
  workflow_call:
    inputs:
      base:
        required: true
        type: string
      target:
        required: true
        type: string
      skip_ci:
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      base:
        required: true
        description: "Base branch to Sync"
        type: string
      target:
        required: true
        description: "Target branch to Sync"
        type: string
      skip_ci:
        required: true
        description: "Should push skip CI"
        type: boolean
        default: true

env:
  message: "Auto Sync with ${{ inputs.base }}"
  base: ${{ github.event.inputs.base || inputs.base }}
  target: ${{ github.event.inputs.target || inputs.target }}

jobs:
  sync:
    name: Sync Branches ♾️
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set Automation
        if: ${{ inputs.skip_ci }}
        run: |
          skip_ci=" [skip-ci]"
          echo "message=$message$skip_ci" >> $GITHUB_ENV
      - name: Sync Branches
        run: |
          git config user.email $git_email
          git config user.name $git_actor
          git branch
          git fetch origin ${{ env.target }}
          git checkout ${{ env.target }}
          git pull
          git merge ${{ env.base }} --allow-unrelated-histories
          git push
        shell: bash
        env:
          git_email: "${{ github.actor }}@users.noreply.github.com"
          git_actor: "${{ github.actor }}"